### ISSUE TITLE
Display tickets that I'm allowed to see, not just the ones assigned to me

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/helpdesk#213]
When you as company A provide support to a company B, multiple users in company B may be interacting, accessing to the Portal.

As such, all users in Company B shall be able to display all the tickets associated with their company, and not only the ones assigned to themselves.

This seems to be implemented correctly in the Portal security rules https://github.com/OCA/helpdesk/blob/13.0/helpdesk_mgmt/security/helpdesk_security.xml#L94

But the tickets are not being listed due to https://github.com/OCA/helpdesk/blob/13.0/helpdesk_mgmt/controllers/myaccount.py#L42

In my opinion this should be removed, or replaced by 
domain = [("partner_id", "child_of", partner.commercial_partner_id.id)]

**Comment by JordiBForgeFlow** [comment]
cc @LoisRForgeFlow

**Comment by JordiBForgeFlow** [comment]
@carlos-domatix pehaps you can provide some clarification here?

**Comment by JordiBForgeFlow** [comment]
@eLBati what do you think?

**Comment by mileo** [comment]
I just verified that this problem is true and also occurs in version 12.

You may fix this line too: https://github.com/OCA/helpdesk/blob/13.0/helpdesk_mgmt/controllers/myaccount.py#L15 

![image](https://user-images.githubusercontent.com/1975978/114433698-7da17680-9b98-11eb-9575-f55d9cf4dee6.png)

![image](https://user-images.githubusercontent.com/1975978/114433738-8b56fc00-9b98-11eb-8bed-5e02bc2cc3e1.png)

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/114433885-ba6d6d80-9b98-11eb-8fec-40458f064d31.png)

**Comment by pedrobaeza** [comment]
Why not simply relying on the record rules for each kind of user?

**Comment by JordiBForgeFlow** [comment]
I am preparing a PR

**Comment by LoisRForgeFlow** [comment]
good to close?
