### ISSUE TITLE
Rename module helpdesk to helpdesk_base

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/helpdesk#22]
Odoo Enterprise already has a module called helpdesk. 
To avoid misunderstandings and issues I think it might be better to rename the module as helpdesk_base or something similar.

@aitorbouzas @pedrobaeza What do you think?

**Comment by aitorbouzas** [comment]
If EE's module is called `helpdesk` then you're totally right.
@pedrobaeza is helpdesk_base a good name for this module?

**Comment by pedrobaeza** [comment]
Yes, let's move it to a different name, but I would call it `helpdesk_oca`, as the other one alters the typical use of `base`, that it's `base` + `<name>`, instead of the contrary, and `base_helpdesk` is not the proper name IMO according the intended use of `base`: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#modules.

Other option is to call it `helpdesk_mgmt` (as abbreviation of helpdesk management).

Which one do you prefer?

**Comment by aitorbouzas** [comment]
`helpdesk_mgmt`looks like a better option to me

**Comment by emagdalenaC2i** [comment]
I agree.
`helpdesk_oca` seems to refer to some service provided by OCA.

**Comment by pedrobaeza** [comment]
OK then

**Comment by emagdalenaC2i** [comment]
@aitorbouzas I can create a PR for this if you agree

**Comment by aitorbouzas** [comment]
@emagdalenaC2i sure, thank you!

**Comment by aitorbouzas** [comment]
Close this?
