### ISSUE TITLE
no access to dashboard

### ISSUE THREAD

**Issue by tdombos** [OCA/helpdesk#220]
The following erros message is given if a user that is the member of the User group (not Manager) tries to access the Helpdesk dashboard (app root menu): 

Sorry, you are not allowed to modify documents of type 'Helpdesk Ticket Team' (helpdesk.ticket.team). This operation is allowed for the groups: 	- Helpdesk/Helpdesk Manager - (Operation: write, User: 6)

**Comment by dalonsod** [comment]
Hello @tdombos 
Which Odoo version did you try? And have you tested it on runbot, or locally? 

If it is a local environment, which Helpdesk addons are installed? And ensure that you've got the most recent versions of the addons

**Comment by tdombos** [comment]
v13, I tried on runbot, and the problem is there as well.

**Comment by dalonsod** [comment]
Thanks @tdombos 
Locally tested, the issue is solved making `compute_sudo=True` the `todo_ticket_count*` fields.

I've also notice that #124 is not ported to v13 yet. Those improvements could be made together with the required fix, because they are related to the same part of the code (team computed fields)

**Comment by dalonsod** [comment]
Solved by #222 , this issue can be closed
