### ISSUE TITLE
Users without Helpdesk permissions cannot create timesheet entries on Project

### ISSUE THREAD

**Issue by konykon** [OCA/helpdesk#228]
Impacted versions: 12.0

Steps to reproduce: By installing the following modules, 
```
odoo12-addon-helpdesk-mgmt==12.0.1.22.1
odoo12-addon-helpdesk-mgmt-project==12.0.1.1.0.99.dev6
odoo12-addon-helpdesk-mgmt-timesheet==12.0.1.1.0.99.dev5
odoo12-addon-helpdesk-motive==12.0.1.0.0.99.dev21
odoo12-addon-helpdesk-type==12.0.1.0.0.99.dev24
```
if a user does not have Helpdesk permissions cannot create timesheet entries on Project and the following error appears:  **Access Denied by ACLs for operation: read, uid: 20, model: account.analytic.line, fields: ticket_id, ticket_partner_id**

Current behavior: Users without Helpdesk permissions cannot create timesheet entries on Project

Expected behavior: Users without Helpdesk write permissions can track working time on Project

Video/Screenshot link (optional): 
![Screenshot from 2021-04-26 18-02-56](https://user-images.githubusercontent.com/38106051/116115286-8460db00-a6ba-11eb-8b2f-e9725238c209.jpg)
![Screenshot_2021-04-26 Tasks - Odoo](https://user-images.githubusercontent.com/38106051/116115304-888cf880-a6ba-11eb-8f89-a77ab5ed1f75.jpg)

**Comment by dalonsod** [comment]
@konykon could you try on runbot and check if that issue is reproduced?

**Comment by dalonsod** [comment]
@Yajo this issue is faced with `project_timesheet_time_control` installed, when attempting to start a new timer. Looking at https://github.com/OCA/project/blob/12.0/project_timesheet_time_control/wizards/hr_timesheet_switch.py#L127 , is it possible that a permission error should be fired because of the linked code, if `account.analytic.line` had fields with security groups, like `ticket_id` and `ticket_partner_id`, added by `helpdesk_mgmt_timesheet`? 

In that case, which should be the best solution for this?

**Comment by yajo** [comment]
It depends on whether those fields should be copied over or not. If yes: sudo. If not: add a new method that defines the fields to read, and then fix that line to use that method.

**Comment by konykon** [comment]
@Yajo Could you please explain what do you mean by "should be copied over or not"? Like reproduce the same information, or overwrite it?

**Comment by yajo** [comment]
I mean reproduce the same information, because when you start a new timer, you're actually duplicating the previous one but changing just a few fields. At least, that's how `project_timesheet_time_control` works.
