### ISSUE TITLE
[IMP] access only own team

### ISSUE THREAD

**Issue by tdombos** [OCA/helpdesk#264]
It would be great to have a permission level where the user can only access tickets assigned to the team they are members of.

**Comment by dalonsod** [comment]
Hello @tdombos ,

there's no need to change `helpdesk_mgmt` addon or make a new one, you can make new groups and/or record rules in your Odoo installation in order to achieve it. E.g. if you make a new rule for `helpdesk.ticket` model with this domain, or similar:

`['|',('user_ids','in',[user.id]),('user_ids','=',False)]`

, assign it to `Helpdesk / User` group, and move the `All tickets` rule to `Helpdesk Manager` group, you'll get the desired behavior. Other option should be creating a fourth group, between `User: personal tickets` and `User` groups in the group hierarchy, and creating for it the above rule.

**Comment by tdombos** [comment]
Thank you, that worked, although I also had to add record rules to limit access to helpdesk.ticket.team as well.

**Comment by maininformatica** [comment]
Ok. 
First I create the two rules, it works partially. Only in Dashboard. Then I delete them and everything works fine. I don't get it. I'm also a big newbie. Thank you.
