### ISSUE TITLE
Installation error: the helpdesk_mgmt module conflicts with the maintenance app

### ISSUE THREAD

**Issue by alodoanhnhan** [OCA/helpdesk#267]
I found an error during module installation. Part of the code in the file helpdesk_data.xml has conflicted with the Maintenance app:

        <record id="mail_alias_lead_info_helpdesk" model="mail.alias">
            <field name="alias_name">**helpdesk**</field>
            <field name="alias_model_id" ref="model_helpdesk_ticket" />
            <field name="alias_user_id" ref="base.user_admin" />
            <field name="alias_parent_model_id" ref="model_helpdesk_ticket_team" />
        </record>

You can change the helpdesk name to any other name to avoid conflicts (the alias_name in the model alias.mail must be unique) with the Maintenance module. Then the problem will be solved.

**Comment by dalonsod** [comment]
Hello @alodoanhnhan you're right IMO. Anyway, which Odoo version are you using?

@pedrobaeza `mail_alias_lead_info_helpdesk` record is under a `data noupudate="1"` section. If I made a PR in order to fix it, could you provide me an example of how to upgrade a module with such XML record change and force it during update? Thanks!

**Comment by pedrobaeza** [comment]
https://github.com/OCA/OpenUpgrade/blob/f2bfdfbb1f088f473a4ed319d7ea3e746cb34a7e/addons/account/migrations/13.0.1.1/post-migration.py#L1063

and

https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/noupdate_changes.xml

**Comment by alodoanhnhan** [comment]
Hi @dalonsod , I am using version 14
