### ISSUE TITLE
[14] Disable automatic email notification on new ticket

### ISSUE THREAD

**Issue by GiuTav** [OCA/helpdesk#314]
We would like to avoid that every time a ticket is opened the system sends an email, where can this setting be disabled?
awaiting your reply, I offer cordial greetings

**Comment by dalonsod** [comment]
Hello @GiuTav , I'm not an expert in `mail.thread` model integration, but looking at other implementation and comments, it seems to be a built-in non configurable feature, since `helpdesk.ticket` implements `mail.thread.cc`.

As commented in https://www.odoo.com/forum/help-1/don-t-send-a-message-on-creation-85525 some of the features (like sending an email and others, unfortunately some of them together) can be bypassed with a little effort module, if you need it. Or making a PR improvement with it, of course.

Hope it helps.
