### ISSUE TITLE
OCA-helpdesk doesn't send New Ticket notification email when it's opened from customer portal

### ISSUE THREAD

**Issue by ugoviti** [OCA/helpdesk#363]
Hi,

I'm testing the helpdesk module (great work!) with odoo 15.

All works like a charm, only a question about ticket notification when created from customer portal:

It's possibile to send the ticket mail when customer open a new ticket? 

Let's me explain: If the staff open a ticket using the backend and set the Team and the assigned user, odoo send correctly the notification mail. But this doesn't happen when the customer opens a ticket from his portal.

I searched extensively in the Issue and Pull requests but not found the solution.

I'm missing something? How can I achieve this?

Thank you very much, keep up the good work!

**Comment by unjoss** [comment]
issue confirmed on brand new installed 15 version,  does not send email when created from portal but does send the message if created from backend

**Comment by Romain-Ollink** [comment]
That is exactly the same for me, what can we do to solve this issue ?
It's the same for Odoo 14

**Comment by Romain-Ollink** [comment]
The reason is that the email is created to be sent by the ticket user, since the customers' email domain is not the one configured by odoo the email cannot be sent.
We must force the email template to send the ticket creation email from a customer to an address of our choice. But I do not know how...
![image](https://user-images.githubusercontent.com/126860959/222706834-5c2e1bdb-91ec-4214-8a82-0f59da532f9d.png)

**Comment by lk-eska** [comment]
These are already sorted out in version 12.0. There is a commit which forward ports this and many other fixes but it wasn't accepted:

https://github.com/OCA/helpdesk/pull/448/commits/dc3cdf9346dc50d03006876960fe9f9f6b77e5ac#diff-bcc3e70daeb2061b18109ace4a025610c738c54700a69b0e673cdd6c151366bf
