### ISSUE TITLE
[14.0] Can't open ticket if there are logged hours when using permission group for personal tickets only

### ISSUE THREAD

**Issue by brenoalef** [OCA/helpdesk#390]
## Module
helpdesk_mgmt_timesheet

## Describe the bug
If a user is in the permission group of personal tickets and has permission to read analytic lines, the system outputs an error message when the user tries to read a ticket with logged hours. This happens because the module restricts the field `ticket_id` in the class `AccountAnalyticLine` to the group `group_helpdesk_user` (User with access to all tickets), so users in the group `group_helpdesk_user_own` can't access it.  
Additionally, in the same way, users in the second group can't see the filters defined in `hr_timesheet_view.xml` because of the restriction set to `group_helpdesk_user` only.

## To Reproduce
**14.0**:

1. Grant access to a user to read analytic lines (e.g., Manager of Project module) and read all tickets
2. Log hours in a ticket
3. Change user permission to access personal tickets only
4. Try to open the ticket again
5. See the error saying the field `ticket_id` is only readable by users in the group `group_helpdesk_user`

**Expected behavior**
Users in the group with access to personal tickets only and access to analytic lines should be able to read tickets without errors.

**Comment by dalonsod** [comment]
Hello @brenoalef ,

inspecting original v12 code, I've not found anything that could justify using `group_helpdesk_user` instead of `group_helpdesk_user_own` (at the bottom of the Helpdesk security groups hierarchy). And no problems should be arise with this change IMO.

Making that little change, or even removing `groups` definition for affected fields (and using instead view security restriction) could fix that bug.
